CREATE TABLE provincies (
    codi INT,
    nom VARCHAR(22) CHARACTER SET utf8
);

INSERT INTO provincies VALUES (08,'BARCELONA');
INSERT INTO provincies VALUES (17,'GIRONA');
INSERT INTO provincies VALUES (25,'LLEIDA');
INSERT INTO provincies VALUES (43,'TARRAGONA');
